#application-containers.yaml
spring:
  datasource:
    url: jdbc:tc:postgresql:16.3:///testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  test:
    database:
      replace: none