#application-containers.yaml
spring:
  datasource:
    url: jdbc:tc:postgresql:16.3:///testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  test:
    database:
      replace: none
  security:
    oauth2:
       resourceserver:
         jwt:
           issuer-uri: http://localhost:8081/realms/myrealm
           jwk-set-uri: http://localhost:8081/realms/myrealm/protocol/openid-connect/certs