#application-local.yaml
spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/myrealm
          jwk-set-uri: http://localhost:8081/realms/myrealm/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:mem:myfintechdb
    driver-class-name: org.h2.Driver
    username: user
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: true
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
