name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn -B clean verify
        
      - name: Upload JaCoCo Report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
          
      - name: Generate JaCoCo Badge and Coverage PR Comment
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-report-path: target/site/jacoco/jacoco.xml
          generate-coverage-badge: true
          generate-coverage-summary: true


